name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: eclipse-temurin:21-jdk-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: '3.9.6'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
         
      - name: Build and install with Maven
        run: mvn clean install -B -V

      - name: Run checkstyle
        run: mvn checkstyle:check

      - name: Run tests with Jacoco
        run: mvn test jacoco:report